### ISSUE TITLE
Suggest yahnc app when user clicks on news.ycombinator.com link

### ISSUE THREAD

**Issue by arkadiytehgraet** [mitya1337/yahnc#18]
Когда пользователь кликает на ссылку http://news.ycombinator.com на своём девайсе, нужно предлагать открывать её в приложении. Если по ссылке была конкретная новость - запускать StoryActivity c этой новостью.

Чё читать: вот [этот ответ](http://stackoverflow.com/questions/3469908/make-a-link-in-the-android-browser-start-up-my-app/3472228#3472228) на стаковерфлоу.

**Comment by mitya1337** [comment]
Тестовая ссылка
https://news.ycombinator.com/item?id=12109199
