### ISSUE TITLE
Add toolbar with activity name and refresh icon

### ISSUE THREAD

**Issue by arkadiytehgraet** [mitya1337/yahnc#2]
Нужно добавить тулбар в лейаут главной активити; в коде нужно установить имя активити и добавить рефреш иконку с пустым обработчиком нажатия на него.

Чё читать - https://developer.android.com/guide/topics/ui/declaring-layout.html , https://developer.android.com/training/appbar/index.html  https://developer.android.com/training/improving-layouts/reusing-layouts.html http://tools.android.com/tech-docs/new-build-system/user-guide
https://developer.android.com/topic/libraries/support-library/features.html

Чё знать - как добавлять элементы в лейаут, как его устанавливать для активити, как находить и использовать его элементы в коде; что такое тулбар, как добавлять туда айтемы и как обрабатывать их нажатия (очень желательно знать, что такое акшонБар, почему он сосёт и чем хуже тулбара); что такое градл, как добавить зависимость в проект в градле; что такое AppCompat, зачем он нужен, что такое обратная совместимость, какие фичи доступны каким версиям ведра.

**Comment by fominok** [comment]
посоны а че меня не позвали
